# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15zYuc6pAgfeSHEUzPqiEC2AiIIpdvGMi
"""

#Python If-Else

n=int(input())
if n/2==0:
  print('Weird')
elif n/2==0 and 2 <=n <=5:
  print('Not Weird')
elif n/2==0 and 6<= n <=20:
  print('Weird')
else:
  print('Not Weird')

