# -*- coding: utf-8 -*-
"""House.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15zYuc6pAgfeSHEUzPqiEC2AiIIpdvGMi
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
from google.colab import files
uploaded=files.upload()

import io
df=pd.read_csv(io.BytesIO(uploaded['House.csv']))
df

x=df[['Area']]
y=df['Price']
plt.plot(y,x)
plt.show()

plt.xlabel('area')
plt.ylabel('price')
plt.title('area-price')
plt.scatter(x,y,marker='+' , color='b')

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=1)

from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(xtrain,ytrain)

reg.predict(xtest)

reg.predict([[3500]])

reg.coef_

reg.score(x,y)

