# -*- coding: utf-8 -*-
"""Self.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DuNW6nV1EA_1YgZ71AZyflH4ZGrqT6Ep
"""

#Python If-Else

n=int(input())
if n/2==0:
  print('Weird')
elif n/2==0 and 2 <=n <=5:
  print('Not Weird')
elif n/2==0 and 6<= n <=20:
  print('Weird')
else:
  print('Not Weird')

#Arithmetic Operators
a, b = int(input()), int(input())
print((a + b), (a - b), (a * b), sep='\n')

#Python: Division
a,b=int(input()),int(input())
print((a//b),(a/b),sep="\n")

#Loops
n=int(input())
for i in range(n):
  print(i ** 2)

def is_leap(year):
    leap = False
    
    # Write your logic here
    if year%400==0 :
        leap = True
    elif year%4 == 0 and year%100 != 0:
        leap = True
    return leap

year = int(input())
print(is_leap(year))

n=int(input( ))
for i in range(1,n+1):
  print(i,end="")

c=int(input())
f=int(input())
f=((c * 9)/5) +32
c=((f-32)*5)/9
print(f)
print(c)

x, y, z, n = int(input()), int(input()), int(input()), int(input())
print ([[a,b,c] for a in range(0,x+1) for b in range(0,y+1) for c in range(0,z+1) if a + b + c != n ])

x=int(input())
y=int(input())
z=int(input())
n=int(input())
print ([[a,b,c] for a in range(0,x+1) for b in range(0,y+1) for c in range(0,z+1) if a + b + c != n ])

n = int(input())

if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())
    print (sorted(set(arr))[-2])



